<?php

namespace DAO;


class ReporteDAO extends CoreDAO
{
    public function __construct($db, $table)
    {
        parent::__construct($db, $table);
    }

    function getPager($limit, $actualPage, $paddingPages)
    {
        return parent::getPager($limit, $actualPage, $paddingPages); // TODO: Change the autogenerated stub
    }

    function process(&$result, $item)
    {
        parent::process($result, $item); // TODO: Change the autogenerated stub
    }

    function read($object = array(), $sqlExtra = "", $offset = 0, $limit = false, $joinSql = false)
    {
        return parent::read($object, $sqlExtra, $offset, $limit, $joinSql); // TODO: Change the autogenerated stub
    }

    protected function update($object)
    {


        return parent::update($object); // TODO: Change the autogenerated stub
    }

    function attach($id, $adjuntos)
    {
        return parent::attach($id, $adjuntos); // TODO: Change the autogenerated stub
    }

    function getKeys($object)
    {
        return parent::getKeys($object); // TODO: Change the autogenerated stub
    }

    function insert($object)
    {


     if(!$object["reporte_fecha"])
     {
         if($object["array"])
         {



             foreach($object["array"] as $k=>$v)
             {
               if(!$object["array"][$k]["reporte_fecha"])
               {
                   $object["array"][$k]["reporte_fecha"]=time();
               }
             }



         }
         else
         {
                 $object["reporte_fecha"]=time();

         }

     }



        return parent::insert($object); // TODO: Change the autogenerated stub
    }

    function upsert($object, ArchivoDAO $archivoData = null)
    {


        include (ROOT_DIR."flush-territorios-cache.php");

        return parent::upsert($object, $archivoData); // TODO: Change the autogenerated stub
    }

    function delete($object)
    {
        include (ROOT_DIR."flush-territorios-cache.php");
        return parent::delete($object); // TODO: Change the autogenerated stub
    }

}
?>